# Generated by Django 5.0.3 on 2024-04-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_register_email_alter_register_email2_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
