# Generated by Django 5.0.3 on 2024-04-12 18:41

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='number',
            field=models.CharField(max_length=200, validators=[tasks.models.validate_number]),
        ),
    ]
