# Generated by Django 5.0.3 on 2024-04-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_register_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
