# Generated by Django 5.0.3 on 2024-04-12 18:44

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200, validators=[tasks.models.validate_number])),
                ('email', models.EmailField(max_length=200)),
                ('email2', models.EmailField(max_length=200)),
                ('psw', models.CharField(max_length=200)),
                ('pwd2', models.CharField(max_length=200)),
            ],
        ),
    ]
