# Generated by Django 5.0.4 on 2024-04-17 14:24

import django.core.validators
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=200, unique=True, validators=[django.core.validators.EmailValidator(message='Ingrese un correo válido.')]),
        ),
        migrations.AlterField(
            model_name='register',
            name='email2',
            field=models.EmailField(max_length=200, unique=True, validators=[django.core.validators.EmailValidator(message='Ingrese un correo válido.')]),
        ),
        migrations.AlterField(
            model_name='register',
            name='number',
            field=models.CharField(max_length=200, unique=True, validators=[tasks.models.validate_number]),
        ),
        migrations.AlterField(
            model_name='register',
            name='psw',
            field=models.CharField(max_length=200, validators=[tasks.models.validate_password]),
        ),
    ]
