# Generated by Django 5.0.3 on 2024-04-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_profile_email_profile_name_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
