# Generated by Django 5.0.3 on 2024-04-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
