# Generated by Django 5.0.3 on 2024-04-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
