# Generated by Django 5.0.4 on 2024-04-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_remove_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='register',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='photo',
            field=models.ImageField(blank=True, default='./frontEndApp/asset/images/foto_perfil/perfil.jpg', upload_to='photos_profile'),
        ),
        migrations.AddField(
            model_name='register',
            name='postal_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
