<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-05-06 09:18
=======
# Generated by Django 5.0.3 on 2024-05-03 07:46
>>>>>>> caa6c9cd43caf1f3939f6ab14e8c46ccab5965ee

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_register_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='register',
            name='pwd2',
        ),
    ]
