# Generated by Django 5.0.3 on 2024-05-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
